### ISSUE TITLE
allow turning off beep

### ISSUE THREAD

**Issue by quite** [peterh/liner#124]
I'd like an option to turn off the beeping. Would a `func (s *State) SetBeep(bool)` do? Default `true`.

**Comment by peterh** [comment]
I wouldn't reject a pull request, but I would prefer you to turn off the beep in xterm (or whatever you're using) instead of liner.

**Comment by quite** [comment]
I think it makes sense to allow programs that use liner to set this (for example making it configurable). See #125

**Comment by peterh** [comment]
Merged #125 . Thanks for the patch.
