### ISSUE TITLE
Problem: wrap a NewCli

### ISSUE THREAD

**Issue by jievince** [peterh/liner#134]
when I wrap newLiner into a function, auto-completions shows some bug.
when I type `TAB`, it doesn't do a completion but a real `TAB`(4 spaces).
![image](https://user-images.githubusercontent.com/38901892/90588872-48ae7100-e20f-11ea-9f63-84ae19389fd8.png)

**Comment by jievince** [comment]
![image](https://user-images.githubusercontent.com/38901892/90589123-ebff8600-e20f-11ea-8ab6-d389ed7d347b.png)

**Comment by peterh** [comment]
defer line.Close() in newCli is closing line. We should probably panic when you call line.Prompt after closing line.

**Comment by jievince** [comment]
@peterh
