### ISSUE TITLE
Support colorful prompt

### ISSUE THREAD

**Issue by jievince** [peterh/liner#135]
liner doesn't support colorful prompt now:
```go
func (s *State) PromptWithSuggestion(prompt string, text string, pos int) (string, error) {
	for _, r := range prompt {
		if unicode.Is(unicode.C, r) {
			return "", ErrInvalidPrompt
		}
	}
```
Why liner doesn't prompt like `\033[31;1m\033[0m` ?

**Comment by jievince** [comment]
@peterh

**Comment by peterh** [comment]
Liner doesn't support \033 because it's not portable. Specifically, Windows doesn't support VT102 escape sequences. It has a completely different API.

If you want colour, you want something more powerful (and less opinionated) than liner.
