### ISSUE TITLE
Prompt does not appear in git bash

### ISSUE THREAD

**Issue by vintingb** [peterh/liner#144]
- Operating System : Windows
- version : v1.2.1
Prompt does not appear in git bash
![powershell](https://user-images.githubusercontent.com/54710337/102497641-ddd54f80-40b3-11eb-993d-a69e99244a14.png)
![wsl](https://user-images.githubusercontent.com/54710337/102497684-e9c11180-40b3-11eb-9148-2817b673aa18.png)
![git](https://user-images.githubusercontent.com/54710337/102497711-f0e81f80-40b3-11eb-9bb3-5362e3ada4bd.png)

**Comment by jcburley** [comment]
I've noticed this and seen similar problems with the Git Bash environment (which I think is actually MingW32?), such as a different Go-based line-reader library just exiting right during/after prompting, before accepting any input.

So I'm not convinced this is really a bug in liner so much as a compatibility issue in MingW32 or whatever underlies Git Bash.
