### ISSUE TITLE
Add an example for filepath tab completion

### ISSUE THREAD

**Issue by krasi-georgiev** [peterh/liner#156]
Would you consider adding an example for a prompt that auto completed file names on tab presses?

**Comment by peterh** [comment]
I would consider adding such an example if it is small and to the point. My main concern is that proper filesystem access often requires much error checking, which might make the example more about the filesystem access and less about liner.

**Comment by krasi-georgiev** [comment]
Could you share  some code here as a starting point and I will use it to see if it turns out to be working well or not

**Comment by peterh** [comment]
Sorry, I misunderstood. I thought you offering to write an example for others.

**Comment by krasi-georgiev** [comment]
yeah I thought this is a common feature so was hoping someone already wrote it.
