### ISSUE TITLE
Convert constants to variables

### ISSUE THREAD

**Issue by ElPincheTopo** [peterh/liner#33]
I know one of the objectives of the project is to keep it simple and limit the configuration options in order to do so. But it would be very useful for some users to be able to change the HistoryLimit and KillRingMax constants. What do you think about it?

**Comment by peterh** [comment]
Does "Some users" include you, or are you talking about hypothetical users? If it's a feature for imaginary users, it's not worth the extra complexity for no benefit.

If it's something you'd actually use, I would be open to a pull request that:
* Adds functions to change the history limit and kill-ring-max of a liner (trimming each if necessary)
* Updates the documentation of HistoryLimit and KillRingMax to indicate that they are default limits
