### ISSUE TITLE
Support multiline editing

### ISSUE THREAD

**Issue by pires** [peterh/liner#55]
For instance, to be used in https://github.com/influxdb/influxdb/issues/4279.

**Comment by flisky** [comment]
I'm working on it, and a PR is coming in a few hours:)

**Comment by peterh** [comment]
I consider multi-line editing to be out of scope for liner, but maybe I'll be amazed by your patch. I look forward to seeing it.

Don't forget to test Linux (with TERM=xterm), Linux (with TERM=dumb) and Windows.

**Comment by peterh** [comment]
And, since I was just looking at it, don't forget to test history saving/loading (which uses `\n` as a delimiter).

**Comment by flisky** [comment]
PR #59. Will self review the code and do more tests soon.

I take more care on double width char, because I use English and Chinese both.

Any suggestion is welcome, specifically on the variable naming, which bother me much:)
