### ISSUE TITLE
Expose HistoryLimit

### ISSUE THREAD

**Issue by ikandaswamy** [peterh/liner#63]
Hi,
Is it possible to have the value of the HistoryLimit be exposed ? I wanted to set the limit based on user input. 

Thanks

**Comment by peterh** [comment]
HistoryLimit has to remain a constant to preserve the API.

A function to change the History Limit of a given state is possible, but it's not completely trivial. For example, when you submit your pull request please add a test for the outcome of reducing the history limit of a State that already contains more history than the new limit.
