### ISSUE TITLE
Liner becomes confused when recalling multi-line items from history

### ISSUE THREAD

**Issue by knz** [peterh/liner#68]
Steps to reproduce:
- save a multi-line item to history
- recall multi-line item from history

At this point navigation of the multi-line item is messed up. 

Moreover, if the prompt is already at the bottom of the terminal, the terminal gets messed up as well (cursor blocked at bottom while the lines above it get updated).

**Comment by peterh** [comment]
Multi-line is messed up how? I can't seem to reproduce either "messed up" or "cursor blocked" on Windows 10 / Comand Prompt or Deiban Stable / xfce4-terminal.

CC: @flisky since Flisky wrote Multi-Line mode.

**Comment by flisky** [comment]
Sorry, I'm in the Chinese Spring Festival holiday.

@knz, could you please reproduce this using something like `asciinema`?

BTW, the `linenoise`  doesn't seem to work perfectly with CJK characters, just FYI.

**Comment by peterh** [comment]
Not reproducible and no response from @knz. Assuming original report is mistaken.
