### ISSUE TITLE
liner used in https://github.com/jyrgenn/lingo

### ISSUE THREAD

**Issue by jyrgenn** [peterh/liner#73]
(Sorry for abusing the issue mechanism; I am not overly familiar with Github and didn't find another way to to reach you.)

I just wanted to let me know that I use your "liner" as the input line editor for my Lisp interpreter in Go "lingo" <https://github.com/jyrgenn/lingo>. Lingo is just a toy project, and I didn't want to put much time into a component that is not so closely related, programming-wise, to what I wanted to do playing around with implementing (yet another) Lisp.

So, thanks for "liner"! It is just what I was looking for, and I was able to put it to good use fast thanks to the good documentation and the example.

Best wishes, Juergen.
(And of course you can close this issue immediately. :–)

**Comment by peterh** [comment]
Thank you for the kind words.
