### ISSUE TITLE
When scrolling through history the previous line on the terminal is overwritten

### ISSUE THREAD

**Issue by ikandaswamy** [peterh/liner#78]
Bug report
- Operating System : Mac
- Terminal Emulator : xterm
- Bug behaviour and Expected behaviour : 
  When scrolling through history, the previous line is overwritten. 
  Previously did not overwrite the previous line on the terminal. Now with every couple of scrolls it overwrites the previous line. 
- Caused by : 
  https://github.com/peterh/liner/commit/0e4af131b90a9786839c8b1b01717be263e8555a
  After I removed the above checkin i did not see the issue again. 

-Sample Example : 
In the beginning it looked like -> 
Connected to : http://localhost:8091/. Type Ctrl-D or \QUIT to exit.

**Path to history file for the shell : /Users/isha/.cbq_history** 
cbq> 

After scrolling through history a bit then it eats up a previous line 
Connected to : http://localhost:8091/. Type Ctrl-D or \QUIT to exit.

cbq> CREATE INDEX ......

The above Path to ... line is replaced. 

Thanks
Isha

**Comment by peterh** [comment]
Sorry for the late reply.

To clarify, are you really using xterm (presumably on XQuartz) on Mac, and not Terminal.app?

Unfortunately, I don't have easy access to a Mac these days, so it may be a while before I can look into this in detail.

**Comment by peterh** [comment]
No response from reporter.
