### ISSUE TITLE
Input is slow

### ISSUE THREAD

**Issue by Hellsegga** [peterh/liner#81]
Hello,

Thanks for this library.
As noticed in this [issue](https://github.com/ethereum/go-ethereum/issues/2938) on the go-ethereum project, liner is quite slow in processing the input, which is noticeable when pasting large amounts of data. For example pasting 30KB takes up to 1 minute. In comparison linenoise takes a few seconds.
Maybe the "refresh" functions could be optimized somehow to speed it up?

**Comment by peterh** [comment]
Sorry for the slow response.

I had some time to work on liner today. It should be significantly faster on large input now. Please update liner and let me know.
