### ISSUE TITLE
s.winch undefined

### ISSUE THREAD

**Issue by tleb** [peterh/liner#93]
Here is the complete error:

```
..\..\peterh\liner\line.go:600:10: s.winch undefined (type *State has no field or method winch)
```

- Windows
- babun

Got this error while running `go get -u github.com/motemen/gore`.

It it linked to this commit: ccfc1e0e5477b6dc05c547998bf2e032bb1bec40.

**Comment by peterh** [comment]
Oops, I should have checked the pull request more carefully. Sorry about that.

I've reverted the offending commit.

**Comment by tleb** [comment]
Great, thanks. :)
