### ISSUE TITLE
Delete next word

### ISSUE THREAD

**Issue by maxp-edcast** [peterh/liner#94]
I came across this repo in hopes of understandinf how to use the InfluxDB CLI, which uses it. 

I noticed that there is no way listed on the README to delete the next word after the cursor. I typically only use this to delete words, and never delete the previous word (it's just a personal habit). 

Is there a way to get this functionality?

**Comment by peterh** [comment]
We could probably add that. What keystroke do you expect will "delete next word"? A bit of googling around suggests `Alt-D`.

**Comment by maxp-edcast** [comment]
Yeah I think Alt-D is standard.

On OSX it's Option-D, but I have no idea if there is any difference in terms of the underlying implementation. Thanks a lot for being responsive.

**Comment by maxp-edcast** [comment]
Wow thanks so much.
