### ISSUE TITLE
cygwin/mingw support?

### ISSUE THREAD

**Issue by filimonov** [peterh/liner#95]
liner doesn't work properly in cygwin / mingw environment on Windows: it allows cursor to scroll on the whole window, doesn't show prompt, etc.

Generally cygwin / mingw behaves as normal terminal, so code which is used on *nix systems (ANSI control sequence based) should just work.

**Comment by peterh** [comment]
Liner works fine in a cygwin/mingw environment that is running in the Windows Console.

If you mean "liner doesn't work in mintty", that's because mintty does not provide a complete Windows Console environment. Please file a bug against mintty.
