### ISSUE TITLE
liner not work properly in mintty (on Windows)

### ISSUE THREAD

**Issue by filimonov** [peterh/liner#96]
- Operating System: **Windows**
- Terminal Emulator: **mintty** (and more generally - terminal Emulators running on Windows without support of native Windows API for command-line, but with ANSI control codes support)
- Bug behaviour: **generally malfunction**: liner doesn't control terminal window: no prompt, you can move cursor at the any place of the screen, etc.
- Expected behaviour: **normal work** transparently - with detection of terminals without Windows API support **OR** ability to force ANSI terminal mode on Windows (like `liner.ForceAnsiTerminalMode(1)`), **OR** documentation with description of possible workarounds for such terminals (like winpty)
- Complete sample that reproduces the bug: use "Getting started" sample

See also: https://github.com/mintty/mintty/wiki/Tips#inputoutput-interaction-with-alien-programs

**Comment by peterh** [comment]
Sorry, when I said "report this against mintty" I meant go to the mintty project and report a bug there.

By the link you referenced here, this is a known issue with mintty. They suggest using winpty as a workaround for their bug. I don't know if it works, but if it doesn't, you should take this up with them.

This is not a bug in Liner.
