### ISSUE TITLE
How to reserve previous content  in the same line

### ISSUE THREAD

**Issue by yc90s** [peterh/liner#97]
## Description
liner will overwrite the same line of output. How can I reserve the previous content?

## Example
```
line := liner.NewLiner()
defer line.Close()

fmt.Print("===don't overwrite this=== ")
if name, err := line.Prompt("What is your name? "); err != nil {
      log.Println(err)
} 
```
When you enter a `<Backspace>`, the content will be overwirted.

**Comment by peterh** [comment]
Liner controls the entire command line. If you want something to appear before the editable field, it must be a part of the prompt.

eg. your example would be

**Comment by peterh** [comment]
eg. your example would be
```
prefix := "===don't overwrite this=== "
line.Prompt(prefix + "What is your name? ")
```

**Comment by yc90s** [comment]
Can't join it to the prompt, because it's printed somewhere else. Anyway, thank you for reply
