### ISSUE TITLE
Input problem on Windows

### ISSUE THREAD

**Issue by iikira** [peterh/liner#99]
- Operating System: Windows 10 (64-bit), Windows xp (32-bit)
- Terminal Emulator: Command Prompt, PowerShell
- Bug behaviour: Cannot input character which greater than "\u7fff" on Windows. 
Test characters: "翽翾翿耀老" ("\u7ffd\u7ffe\u7fff\u8000\u8001").
I copied test characters to clipboard and pasted it, and the result was in the following screenshot.
<img width="351" alt="2018-01-28 2 05 41" src="https://user-images.githubusercontent.com/19154488/35479604-95a9e728-0436-11e8-94db-94c35287b6ff.png">

But it work fine on OS X and Linux.

- Expected behaviour: Can input character which greater than "\u7fff" on Windows.
- Complete sample that reproduces the bug
```go
package main

import (
	"fmt"
	"github.com/peterh/liner"
)

func main() {
	fmt.Println("\u7ffd\u7ffe\u7fff\u8000\u8001")
	line := liner.NewLiner()
	defer line.Close()
	input, _ := line.Prompt("input: ")
	fmt.Println(input)
}

```

**Comment by peterh** [comment]
Thanks for the clear bug report and reproduction example.
